In [4]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import os
from scipy.stats import multivariate_normal as mvn
from scipy.stats import multinomial as mlvn
from scipy.stats import bernoulli as brn
%matplotlib inline

In [11]:
data=pd.read_csv("MNIST_train.CSV")
df=data
data2=pd.read_csv("MNIST_test.CSV")
df2=data2

In [9]:
class GenBayes():
    
    def fit (self, X, y, DistStr, epsilon=1e-3):
    # epsilon is the default value  #DistStr is the distribution, 
    #it is what the data looks like( e.g. gaussian, binoamial or bernouli, trinomial, etc..multi variate, etc#
    #.. this is new to this model)
    
    # preallocating the two dictionaries we are going to populate later 
        self.likelihoods=dict()
    
        self.priors=dict()
    
        self.K=set(y.astype(int))
    
        if DistStr=="Gauss":
        
            for k in self.K:
            
                X_=X[y==k,:]
            
                N_k, D =X_k.shape
            
                mu_k=X_k.mean(axis=0)
            
            self.likelihoods[k]={"mean":X_k(axis=0), "cov":(1/(N_k-1)
                                *np.matmul((X_k -mu_k).T),X_k-mu_k)+
                                epsilon*np.identity(D)}
            
            self.priors[k]=len(X_k)/len(X)
            
            
        
        if DistStr=="Multinomial":
        
            for k in self.K:
            
                X_k=X[y==k,:]
            
                N_k, D =X_k.shape
            
                mu_k=X_k.mean(axis=0)
                
                N=len(X)
                
                self.likelihoods[k]={"N":N, "P":sum(N_k/len(X))}
                
                self.priors[k]= len(x_k)/len(X)
                
        
        if DistStr=="Bernolli":
        
                for k in self.K:
                
                    X_k=X[y==k,:]
                
                    N_k, D= X_k.shape
                
                    self.likelihoods[k]= {"P": N_k/len(X)}
                
                    self.priors[k]= len(X_k)/len(X)
                
                
                
        def predict(self, X, DistStr):
            
            N, D= X.shape
            
            if DistStr=="Gauss":
                
                P_hat=np.zeros((N, len(self.k)))
                
                
                for k,l in selflikelihoods.items():
                    
                    P_hat[:,k]= mvn.logpdf(X,l["mean"],l["cov"])+np.log(self.priors[k])
                    
                return P_hat.argmax(axis=1)
            
            if DistStr=="Multinomial":
                
                P_hat= np.zeros((N, len(self.k)))
                
                
                for k,l in self.likelihoods.items():
                    
                    P_hat[:,k]= mlvn.logpdf(X,l["N"],l["P"])+ np.log(self.priors[k])
                    
                return P_hat.argmax(axis=1)
            
            if Diststr=="Bernoulli":
                
                P_hat=np.zeros((N, len(self.k)))
                
                for k,l in self.likelihood.items(): 
                    
                    P_hat[:,k]= bernoulli. logpdf(X, l["p"])+np.log(self.priors[k])
                    
                return P_hat.argmax(axis=1)  

In [8]:
df.head()

Unnamed: 0  index  labels  0  1  2  3  4  5  6  ...  774  775  776  777  \
0           0      0       7  0  0  0  0  0  0  0  ...    0    0    0    0   
1           1      1       2  0  0  0  0  0  0  0  ...    0    0    0    0   
2           2      2       1  0  0  0  0  0  0  0  ...    0    0    0    0   
3           3      3       0  0  0  0  0  0  0  0  ...    0    0    0    0   
4           4      4       4  0  0  0  0  0  0  0  ...    0    0    0    0   

   778  779  780  781  782  783  
0    0    0    0    0    0    0  
1    0    0    0    0    0    0  
2    0    0    0    0    0    0  
3    0    0    0    0    0    0  
4    0    0    0    0    0    0  

[5 rows x 787 columns]

In [12]:
df.shape

(60000, 787)

In [13]:
df2.shape

(10000, 787)

In [14]:
X=df[:,3:]

TypeError: '(slice(None, None, None), slice(3, None, None))' is an invalid key

In [37]:
X=data.to_numpy()

In [38]:
X

array([[    0,     0,     5, ...,     0,     0,     0],
       [    1,     1,     0, ...,     0,     0,     0],
       [    2,     2,     4, ...,     0,     0,     0],
       ...,
       [59997, 59997,     5, ...,     0,     0,     0],
       [59998, 59998,     6, ...,     0,     0,     0],
       [59999, 59999,     8, ...,     0,     0,     0]], dtype=int64)

In [39]:
X.shape

(60000, 787)

In [31]:
#X= X[:,3:]

In [32]:
#y=X[:,2]

In [40]:
y=X[:,2]

In [41]:
y

array([5, 0, 4, ..., 5, 6, 8], dtype=int64)

In [42]:
print(y)

[5 0 4 ... 5 6 8]


In [43]:
X=[:,3:]

SyntaxError: invalid syntax (<ipython-input-43-1ac1a5a79a16>, line 1)

In [44]:
X=X[:,3:]

In [45]:
X

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [46]:
print(X)

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
