In [ ]:
list are ordered 

dictionary are faster 
but they make more memory


In [3]:
a_dic = {'A':['value', 0 , 1 , 2 , 3],
         'key':[3 , 4 , 5 , 2, 'A']}

In [4]:
a_dic['A']

['value', 0, 1, 2, 3]

In [5]:
a_dic['A'][0]

'value'

In [2]:
a_dic['key']

'value'

In [ ]:
matrix = [[0 , 3 , 3]
         ,[8, 0 , 9]
         ,[1 , 2 , 3]]

In [7]:
list(zip(*matrix[::-1]))

[(1, 8, 0), (2, 0, 3), (3, 9, 3)]

In [8]:
list(zip(matrix[::-1]))

[([1, 2, 3],), ([8, 0, 9],), ([0, 3, 3],)]

In [ ]:
fir  i,j zip(list1, list2):
    

In [10]:
list1 = [ 3, 4 , 5, 1 ]

In [12]:
for i,item in enumerate(list1):
    print(i , item)
    print(type(i))
    print(type(item))

0 3
<class 'int'>
<class 'int'>
1 4
<class 'int'>
<class 'int'>
2 5
<class 'int'>
<class 'int'>
3 1
<class 'int'>
<class 'int'>


In [15]:
for _ in list1:
    

SyntaxError: unexpected EOF while parsing (<ipython-input-15-d2226d459032>, line 1)

In [17]:
list1 = [ 3, 4 , 5, 1 ]
list2 = [ 1 , 5 , 3 , 9]

In [19]:
list3 = []
for i,j in zip(list1, list2):
    print(i, j)
    list3.append(i , j)

3 1


TypeError: append() takes exactly one argument (2 given)

In [20]:
list3 = []
for i,j in zip(list1, list2):
    print(i, j)
    list3.append([i , j])

3 1
4 5
5 3
1 9


In [21]:
list3

[[3, 1], [4, 5], [5, 3], [1, 9]]

In [22]:

for i in list1:
    for j in list2:
        print(i,j)

3 1
3 5
3 3
3 9
4 1
4 5
4 3
4 9
5 1
5 5
5 3
5 9
1 1
1 5
1 3
1 9


In [ ]:

list node object 

self.next 

In [23]:
     a_dic = {"I":1
                 ,"V":5
                 ,"X":10
                 , "L":50
                 , "C":100
                 , "D":500
                 , "M":1000}
        

In [25]:
input_thing = "III"
for item in input_thing:
    print(item)

I
I
I


In [26]:
# Python program to convert Roman Numerals
# to Numbers

# This function returns value of each Roman symbol


def value(r):
	if (r == 'I'):
		return 1
	if (r == 'V'):
		return 5
	if (r == 'X'):
		return 10
	if (r == 'L'):
		return 50
	if (r == 'C'):
		return 100
	if (r == 'D'):
		return 500
	if (r == 'M'):
		return 1000
	return -1


def romanToDecimal(str):
	res = 0
	i = 0

	while (i < len(str)):

		# Getting value of symbol s[i]
		s1 = value(str[i])

		if (i + 1 < len(str)):

			# Getting value of symbol s[i + 1]
			s2 = value(str[i + 1])

			# Comparing both values
			if (s1 >= s2):

				# Value of current symbol is greater
				# or equal to the next symbol
				res = res + s1
				i = i + 1
			else:

				# Value of current symbol is greater
				# or equal to the next symbol
				res = res + s2 - s1
				i = i + 2
		else:
			res = res + s1
			i = i + 1

	return res


# Driver code
print("Integer form of Roman Numeral is"),
print(romanToDecimal("MCMIV"))


Integer form of Roman Numeral is
1904


In [27]:
def romanToInt(s: str) -> int:
    # Dictionary of roman numerals
    roman_map = {'I': 1, 'V': 5, 'X': 10, 'L': 50, 'C': 100, 'D': 500, 'M': 1000}
    # Length of the given string
    n = len(s)
    # This variable will store result
    num = roman_map[s[n - 1]]
    # Loop for each character from right to left
    for i in range(n - 2, -1, -1):
        # Check if the character at right of current character is bigger or smaller
        if roman_map[s[i]] >= roman_map[s[i + 1]]:
            num += roman_map[s[i]]
        else:
            num -= roman_map[s[i]]
    return num

In [28]:
romanToInt(input_thing)

3

In [29]:
 roman_map = {'I': 1, 'V': 5, 'X': 10, 'L': 50, 'C': 100, 'D': 500, 'M': 1000}

In [30]:
num = len(input_thing)
num

3

In [31]:
num_thing = roman_map[input_thing[num - 1]]
num_thing

1

In [33]:
tur = "VI"
num = len(tur)
num_thing = roman_map[tur[num -1]]
num_thing

1

In [34]:
num

2

In [35]:
some_list = [1 , 3 , 5 , 5]

In [38]:
for item in range(len(some_list)):
    print(item)

0
1
2
3


In [39]:
for item in range(len(some_list) - 2):
    print(item)

0
1


In [40]:
for item in range(len(some_list), -1):
    print(item)

In [41]:
for item in range(len(some_list), -1, -1):
    print(item)

4
3
2
1
0


start: integer starting from which the sequence of integers is to be returned

stop: integer before which the sequence of integers is to be returned.
The range of integers end at stop – 1.

step: integer value which determines the increment between each integer in the sequence

In [42]:
# Python Program to 
# show range() basics 

# printing a number 
for i in range(10): 
	print(i, end =" ") 
print() 

# using range for iteration 
l = [10, 20, 30, 40] 
for i in range(len(l)): 
	print(l[i], end =" ") 
print() 

# performing sum of natural 
# number 
sum = 0
for i in range(1, 11): 
	sum = sum + i 
print("Sum of first 10 natural number :", sum) 


0 1 2 3 4 5 6 7 8 9 
10 20 30 40 
Sum of first 10 natural number : 55


In [43]:
for item in range(lenth_s - 2, -1, -1 ):
            # check character right is biggest
            if a_dic[s[item]] >= a_dic[s[item + 1]]:
                num += a_dic[s[item]]
            else:

SyntaxError: unexpected EOF while parsing (<ipython-input-43-aa6c753df505>, line 5)

In [45]:
def romanToInt(self, s: str) -> int:
        
        a_dic = {"I":1
                 ,"V":5
                 ,"X":10
                 , "L":50
                 , "C":100
                 , "D":500
                 , "M":1000}
        
        #length of input 
        lenth_s = len(s)
        
        #var to store result
        num = a_dic[s[lenth_s - 1]]
        
        #loop though all chars backwards
        for item in range(lenth_s - 2, -1, -1 ):
            # check character right is biggest
            if a_dic[s[item]] >= a_dic[s[item + 1]]:
                num += a_dic[s[item]]
            else:
                num -= a_dic[s[item]]
        return num

In [48]:
s = "VI"

In [50]:
#length of input 
lenth_s = len(s)

#var to store result
num = a_dic[s[lenth_s - 1]]

#loop though all chars backwards
for item in range(lenth_s - 2, -1, -1 ):
    # check character right is biggest
    if a_dic[s[item]] >= a_dic[s[item + 1]]:
        num += a_dic[s[item]]
    else:
        num -= a_dic[s[item]]
print(num)

6


In [ ]:
for item in range(lenth_s - 2, -1, -1 ):
    # check character right is biggest
    if a_dic[s[item]] >= a_dic[s[item + 1]]:
        num += a_dic[s[item]]
    else:
        num -= a_dic[s[item]]

In [51]:
for item in range(len(some_list), -1, -1):
    print(item)

4
3
2
1
0


In [54]:
if a_dic[s[item]] >= a_dic[s[item + 1]]:
        num += a_dic[s[item]]
        
else:
        num -= a_dic[s[item]]

In [58]:
a_dic[s[0]]

5

In [59]:
a_dic[s[1]]

1

In [60]:
#Input: 
strs = ["flower","flow","flight"]
#Output: 
common = "fl"

In [62]:
strs.count('flower')

1

In [63]:
strs.startswith()

AttributeError: 'list' object has no attribute 'startswith'

In [64]:
for item in strs:
    item.startswith('fl')

In [ ]:
Write a function to find the longest common prefix string amongst an array of strings.

If there is no common prefix, return an empty string "".

In [65]:
def longest_Common_Prefix(str1):
    
    if not str1:
        return ""

    short_str = min(str1,key=len)

    for i, char in enumerate(short_str):
        for other in str1:
            if other[i] != char:
                return short_str[:i]

    return short_str 

print(longest_Common_Prefix(["abcdefgh","abcefgh"]))
print(longest_Common_Prefix(["w3r","w3resource"]))
print(longest_Common_Prefix(["Python","PHP", "Perl"]))
print(longest_Common_Prefix(["Python","PHP", "Java"]))

abc
w3r
P



In [66]:
if not strs:
    return ""
short_str = min(str1, key =len)

for i, char in enumerate(short_str):
    for other in strs:
        if other[i] != char:
            print(short_str[:i])

SyntaxError: 'return' outside function (<ipython-input-66-fcfcddefd477>, line 2)

In [68]:
if not strs:
    print(("")
short_str = min(str1, key =len)

for i, char in enumerate(short_str):
    for other in strs:
        if other[i] != char:
            print(short_str[:i])

SyntaxError: invalid syntax (<ipython-input-68-4292e9f86b03>, line 3)

In [69]:
if not strs:
    print(("")
short_str = min(str1, key =len)

for i, char in enumerate(short_str):
    for other in strs:
        if other[i] != char:
            print(short_str[:i])

SyntaxError: invalid syntax (<ipython-input-69-4292e9f86b03>, line 3)

In [70]:
class Solution:
    def longestCommonPrefix(self, strs: List[str]) -> str:
        if len(strs)== 0:
            return ""
        # Optimization 1: Find the string with the min length
        min_length = len(min(strs, key=len))
    
        match_string = ""
        for index in range(min_length):
            # Leverage first word as base case
            letter = strs[0][index]
            match = True
            # Check for a match across index in all words
            for word in strs:
                if word[index] != letter:
                    match = False
            # All a match add letter
            # Optimization 2: else terminate searching
            if match:
                match_string += letter
            else:
                break
                
        return match_string

NameError: name 'List' is not defined

In [71]:
L1 = [1, 2, 3, 4]
L2 = sorted(L1, key=lambda x: -x)  # [4, 3, 2, 1]
L3 = sorted(L1, key=lambda x: x % 2)  # [2, 4, 1, 3]

In [72]:
def shortest_seq(*args):
    return range(len(sorted(args, key=len)[0]))

In [73]:
g = ((names[i], heroes[i]) for i in shortest_seq(names, heroes))
for item in g:
    print(item)

NameError: name 'names' is not defined

In [74]:
shortest_seq(L1)

range(0, 4)

In [75]:
shortest_seq(L2)

range(0, 4)

In [76]:
List = ['a', 'b', 'c']

for i in List:
    print(i)

a
b
c


In [78]:
#compress the for loop into a single statement

LC = [print(i) for i in List]

a
b
c


In [79]:
LC

[None, None, None]

In [ ]:
LC = [print(i) for i in List]

In [80]:
List = ['a', 'b', 'c']
LC = []
for i in List:
    print(i)
    LC.append(i)

a
b
c


In [81]:



LC

['a', 'b', 'c']

In [82]:
#LC = []
LC = [LC.append(i) for i in List]

In [83]:
LC

[None, None, None]

In [84]:
LC = []
LC = [LC.append(i) for i in List]

In [85]:
LC

[None, None, None]

In [86]:
LC = [i for i in List]
LC 

['a', 'b', 'c']

In [87]:
class Human:
    def __init__(self, name, age):
        self.name = name
        self.age = age

    def __repr__(self):
        return f"<Human: {self.name}, {self.age}>"

humans = [
    Human("Alice", 29),
    Human("Bob", 32),
    Human("Charlie", 37),
    Human("Daphne", 30),
    Human("Eve", 26),
    Human("Frank", 18),
    Human("Glenn", 42),
    Human("Harrison", 12),
    Human("Igon", 41),
    Human("David", 31),
]


# Write a list comprehension that creates a list of names of everyone
# whose name starts with 'D':
print("Starts with D:")
a = [d_boi.name for d_boi in humans if d_boi.name[0].lower() == 'd']
print(a)

# Write a list comprehension that creates a list of names of everyone
# whose name ends in "e".
print("Ends with e:")
b = [e_boi.name for e_boi in humans if e_boi.name[-1].lower() == 'e']
print(b)

# Write a list comprehension that creates a list of names of everyone
# whose name starts with any letter between 'C' and 'G' inclusive.
print("Starts between C and G, inclusive:")
import string


alpha_dict = {letter: index for index, letter in enumerate(string.ascii_lowercase)}
c = [c_to_g_boi.name for c_to_g_boi in humans if c_to_g_boi.name[0].lower() in string.ascii_lowercase[alpha_dict['c']:alpha_dict['g'] + 1]]
print(c)

# Write a list comprehension that creates a list of all the ages plus 10.
print("Ages plus 10:")
d = [human.age + 10 for human in humans]
print(d)

# Write a list comprehension that creates a list of strings which are the name
# joined to the age with a hyphen, for example "David-31", for all humans.
print("Name hyphen age:")
e = [f'{human.name}-{human.age}' for human in humans]
print(e)

# Write a list comprehension that creates a list of tuples containing name and
# age, for example ("David", 31), for everyone between the ages of 27 and 32,
# inclusive.
print("Names and ages between 27 and 32:")
f = [(human.name, human.age) for human in humans if human.age >= 27 and human.age <= 32]
print(f)

# Write a list comprehension that creates a list of new Humans like the old
# list, except with all the names uppercase and the ages with 5 added to them.
# The "humans" list should be unmodified.
print("All names uppercase:")
g = [Human(human.name.upper(), human.age + 5) for human in humans]
print(g)

# Write a list comprehension that contains the square root of all the ages.
print("Square root of ages:")
from math import sqrt
h = [sqrt(human.age) for human in humans]
print(h)

Starts with D:
['Daphne', 'David']
Ends with e:
['Alice', 'Charlie', 'Daphne', 'Eve']
Starts between C and G, inclusive:
['Charlie', 'Daphne', 'Eve', 'Frank', 'Glenn', 'David']
Ages plus 10:
[39, 42, 47, 40, 36, 28, 52, 22, 51, 41]
Name hyphen age:
['Alice-29', 'Bob-32', 'Charlie-37', 'Daphne-30', 'Eve-26', 'Frank-18', 'Glenn-42', 'Harrison-12', 'Igon-41', 'David-31']
Names and ages between 27 and 32:
[('Alice', 29), ('Bob', 32), ('Daphne', 30), ('David', 31)]
All names uppercase:
[<Human: ALICE, 34>, <Human: BOB, 37>, <Human: CHARLIE, 42>, <Human: DAPHNE, 35>, <Human: EVE, 31>, <Human: FRANK, 23>, <Human: GLENN, 47>, <Human: HARRISON, 17>, <Human: IGON, 46>, <Human: DAVID, 36>]
Square root of ages:
[5.385164807134504, 5.656854249492381, 6.082762530298219, 5.477225575051661, 5.0990195135927845, 4.242640687119285, 6.48074069840786, 3.4641016151377544, 6.4031242374328485, 5.5677643628300215]


In [88]:
print("Starts with D:")
a = [d_boi.name for d_boi in humans if d_boi.name[0].lower() == 'd']
print(a)

Starts with D:
['Daphne', 'David']


In [89]:
[d.name for d in humans if d.name[0].lower() == 'd']

['Daphne', 'David']

In [ ]:
new_range = [i * i for i in range(5) if i % 2 == 0]

Which corresponds to:

*result* = [*transform* *iteration* *filter* ]

In [ ]:
The basic syntax uses square brackets.

[ expression for item in list if conditional ]
This is equivalent to:

for item in list:
    if conditional:
        expression
Let’s break this down and see what it does.

      
new_list = [expression(i) for i in old_list if filter(i)]
new_list
The new list (result).

expression(i)
Expression is based on the variable used for each element in the old list.

for i in old_list
The word for followed by the variable name to use, followed by the word in the
old list.

if filter(i)
Apply a filter with an If-statement.

This blog shows an example of how to visually break down the list comprehension:

In [95]:
some_str = 'cool stuff'

In [97]:
for y, i in enumerate(some_str):
    #s = i   list[y + i]
    #print(s)
    
    print(y , i )

0 c
1 o
2 o
3 l
4  
5 s
6 t
7 u
8 f
9 f


In [99]:
for y, i in enumerate(some_str):
    #s = i   list[y + i]
    #print(s)
    
    print(i)

c
o
o
l
 
s
t
u
f
f


In [ ]:
list_int = [ 9 , 8 , 3  , 4 , 5 , 6]

In [101]:
for y, i in enumerate(some_str):
    if y < len(some_str - 1):
        s = i - list[y + i]
    print(s)
    
    #print(y , i )

TypeError: unsupported operand type(s) for -: 'str' and 'int'

In [102]:
list_int = [ 9 , 8 , 3  , 4 , 5 , 6]

In [104]:
for y, i in enumerate(list_int):
    if y < len(list_int - 1):
        s = i - list[y + i]
    print(s)
    
    #print(y , i )

TypeError: unsupported operand type(s) for -: 'list' and 'int'

In [105]:
for y, i in enumerate(list_int):
    if y < len(list_int - 1):
        s = i - list(y + i)
    print(s)
    
    #print(y , i )

TypeError: unsupported operand type(s) for -: 'list' and 'int'

In [ ]:
# how to be successful
# minju's app, Social media 2.0
# save people, help people 

# how to do more with less

# survive without pres
#Regression, linear and else wise

# evolve into a better man 


In [ ]:
how best to use these 4 hours 

these 8 hours 



In [ ]:
Presenting cosine lineraity

Review past code 

other maintance activities

array indexing 

jupyter weirdness they discussed

getting better at cooking

In [106]:
nputArray = [3, 6, -2, -5, 7, 3]

In [107]:
def adjacentElementsProduct(inputArray):
    return max(a*b for a, b in zip(inputArray, inputArray[1:]))

In [108]:
adjacentElementsProduct(nputArray)

21

In [109]:
?max()

Object `max()` not found.


In [111]:
help(max(nputArray))

Help on int object:

class int(object)
 |  int([x]) -> integer
 |  int(x, base=10) -> integer
 |  
 |  Convert a number or string to an integer, or return 0 if no arguments
 |  are given.  If x is a number, return x.__int__().  For floating point
 |  numbers, this truncates towards zero.
 |  
 |  If x is not a number or if base is given, then x must be a string,
 |  bytes, or bytearray instance representing an integer literal in the
 |  given base.  The literal can be preceded by '+' or '-' and be surrounded
 |  by whitespace.  The base defaults to 10.  Valid bases are 0 and 2-36.
 |  Base 0 means to interpret the base from the string as an integer literal.
 |  >>> int('0b100', base=0)
 |  4
 |  
 |  Built-in subclasses:
 |      bool
 |  
 |  Methods defined here:
 |  
 |  __abs__(self, /)
 |      abs(self)
 |  
 |  __add__(self, value, /)
 |      Return self+value.
 |  
 |  __and__(self, value, /)
 |      Return self&value.
 |  
 |  __bool__(self, /)
 |      self != 0
 |  
 |  __ceil_

In [112]:
help(max())

TypeError: max expected 1 argument, got 0

In [113]:
?max(nputArray)

Object `max(nputArray)` not found.


In [115]:
nputArray[1:]

[6, -2, -5, 7, 3]

In [116]:
nputArray

[3, 6, -2, -5, 7, 3]

In [ ]:
inputArray[1:]

In [ ]:
zip 
map 
lambda 

In [120]:
max(a*b for a, b in zip(nputArray, nputArray[1:]))

21

Given an array of integers, find the pair of adjacent elements that has the largest product and return that product.

In [ ]:
Given an array of integers, find the pair of non-adjacent elements that has the largest product and return that product.

In [ ]:
max(a*b for a, b in zip(nputArray, nputArray[1:]))

In [121]:
nputArray
#nputArray[1:]

[3, 6, -2, -5, 7, 3]

In [122]:
nputArray[1:]

[6, -2, -5, 7, 3]

Ratiorg got statues of different sizes as a present from CodeMaster for his birthday, each statue having an non-negative integer size. Since he likes to make things perfect, he wants to arrange them from smallest to largest so that each statue will be bigger than the previous one exactly by 1. He may need some additional statues to be able to accomplish that. Help him figure out the minimum number of additional statues needed.

In [124]:
statues = [6, 2, 3, 8]

In [123]:
def makeArrayConsecutive2(statues):


    # a
    statues.sort()
    # b
    fL = 0
    # c
    sL = 1
    lastItem = len(statues)-1
    # d
    differences = 0
    # e
    while (fL <= lastItem - 1) and (sL <= lastItem):
      # f
      if statues[sL] - statues[fL] > 1:
          differences += (statues[sL] - statues[fL] - 1)
      # g
      fL += 1
      sL += 1

    return differences

In [125]:
makeArrayConsecutive2(statues)

3

In [126]:
statues.sort()

In [127]:
statues 

[2, 3, 6, 8]

In [128]:
statues = [6, 2, 3, 8]

In [129]:
statues_sorted = statues.sort()
statues_sorted

In [131]:
print(statues_sorted )

None


In [ ]:
mimize the error , filling out matrix with biasesb


In [132]:
statues

[2, 3, 6, 8]

In [ ]:
Knowledge is knowing a fact 
Wisdom is knowing how to apply that fact 


In [ ]:
def makeconsec(statues):
    
    statues.sort()
    
    

In [ ]:
a) First, sorting the array from least to greatest would make this process simpler, thankfully there's a built in method for that ( called .sort())

b) fL loops from 0 to the second last element in the array (also look at the while statement)

c) sL loops from 1 to the last element in the array (also look at the while statement)

d) the differences variable keeps track of the number of statues needed to fill in between two consecutive numbers so say the numbers were 5 and 9, differences would hold 3 because you need three statues (6,7,8) to go in-between those two numbers.

e) Inside the while loop, it records the number of statues that can go in-between every adjacent pairs.

f) Inside the if statement, if difference between two consecutive number is more than one (ie. The difference between 6 and 7 is 1, but you cant put a statue in-between, so we look for a difference of higher than 1 for each consecutive pairs).

g) fL and sL are incremented by 1 as they continue the loop.

In [ ]:
fl loop from 0 to scd last ele

fl = 0
sl from 1 to the last ele

sl = 0
differences = 0
#e
a whil loop records the in between

#f
if statues[sl] - statues[fl] > 1:
    differences += (statu)

#g
continue to go though loop
fl += 1
sl += 1 

In [ ]:
es.sort()
    # b
    fL = 0
    # c
    sL = 1
    lastItem = len(statues)-1
    # d
    differences = 0
    # e
    while (fL <= lastItem - 1) and (sL <= lastItem):
      # f
      if statues[sL] - statues[fL] > 1:
          differences += (statues[sL] - statues[fL] - 1)
      # g
      fL += 1
      sL += 1

    return differences

In [ ]:
def makeArrayConsecutive2(statues):
    
    statues.sort()
    
    # set variables to go though the array
    first_ele = 0
    second_ele = 1
    # counter for differences in the array
    differences = 0
    
    # for itteration of the while loop
    last_thing = len(statues)-1
    
    while (first_ele <= last_thing -1) and (second_ele <= last_thing):
        
        if statues[first_ele] - statues[second_ele] > 1:
            differences += (statues[first_ele] - statues[second_ele] - 1)
            
        first_ele += 1
        
        second_ele += 1
        
        
    return differences
    

In [133]:
def makeArrayConsecutive2(statues):


    # a
    statues.sort()
    # b
    fL = 0
    # c
    sL = 1
    lastItem = len(statues)-1
    # d
    differences = 0
    # e
    while (fL <= lastItem - 1) and (sL <= lastItem):
      # f
      if statues[sL] - statues[fL] > 1:
          differences += (statues[sL] - statues[fL] - 1)
      # g
      fL += 1
      sL += 1

    return differences

In [134]:
statues
makeArrayConsecutive2(statues)

3

In [135]:
statues

[2, 3, 6, 8]

In [136]:
def makeArrayConsecutive2(statues):
    
    statues.sort()
    
    # set variables to go though the array
    first_ele = 0
    second_ele = 1
    
    
    # for itteration of the while loop
    last_thing = len(statues)-1
    
    # counter for differences in the array
    differences = 0
    
    while (first_ele <= last_thing -1) and (second_ele <= last_thing):
        
        if statues[first_ele] - statues[second_ele] > 1:
            differences += (statues[first_ele] - statues[second_ele] - 1)
            
        first_ele += 1
        
        second_ele += 1
        
        
    return differences

In [138]:
makeArrayConsecutive2(statues)

0

In [141]:
def makeArrayConsecutive2(statues):
    
    statues.sort()
    
    # set variables to go though the array
    first_ele = 0
    second_ele = 1
    
    
    # for itteration of the while loop
    last_thing = len(statues)-1
    
    # counter for differences in the array
    differences = 0
    
    while (first_ele <= last_thing -1) and (second_ele <= last_thing):
        
        if statues[second_ele] - statues[first_ele] > 1:
            differences += (statues[first_ele] - statues[second_ele] - 1)
            
        first_ele += 1
        
        second_ele += 1
        
        
    return differences

In [142]:
makeArrayConsecutive2(statues)

-7

In [143]:
def makeArrayConsecutive2(statues):
    
    statues.sort()
    
    # set variables to go though the array
    first_ele = 0
    second_ele = 1
    
    
    # for itteration of the while loop
    last_thing = len(statues)-1
    
    # counter for differences in the array
    differences = 0
    
    while (first_ele <= last_thing -1) and (second_ele <= last_thing):
        
        if statues[second_ele] - statues[first_ele] > 1:
            differences += (statues[second_ele] - statues[first_ele] - 1)
            
        first_ele += 1
        
        second_ele += 1
        
        
    return differences

In [144]:
makeArrayConsecutive2(statues)

3

In [145]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import os
from scipy.stats import multivariate_normal as mvn
from scipy.stats import multinomial as mlvn
from scipy.stats import bernoulli as brn
%matplotlib inline

In [148]:
class LinearRegression():
    def fit(self, X, y):
        self.w = np.linalg.solve(X.T@X, X.T@y)
        
    def predict(self, X):
        return np.matmul(X, self.w)
#y^ = wX    

In [149]:
statues 

[2, 3, 6, 8]

In [151]:
Linear = LinearRegression()
lin_model = Linear.fit(statues, statues)
y_hat = lin_model.predict(statues)
y_hat

AttributeError: 'list' object has no attribute 'T'

In [154]:
import numpy as np
random_matrix_array = np.random.rand(3)
print(random_matrix_array)

[0.0701547  0.41241787 0.22874376]


In [156]:
import numpy as np
random_matrix_array = np.random.rand(3, 4)
print(random_matrix_array)

[[0.20051783 0.6910462  0.05572179 0.05031819]
 [0.58273555 0.68080108 0.33454905 0.56763461]
 [0.42751074 0.699297   0.7957348  0.65174849]]


In [ ]:
import numpy as np
random_3d_matrix_array = np.random.rand(3, 4, 2)
print(random_3d_matrix_array)

In [152]:
import numpy as np
random_matrix_array = np.random.randint(1,10,size=(3,4))
print(random_matrix_array)

[[7 1 5 6]
 [2 2 2 5]
 [8 3 8 1]]


In [ ]:
import numpy as np
random_matrix_array = np.random.randint(2,size=(3,4))
print(random_matrix_array)

In [153]:
Linear = LinearRegression()
lin_model = Linear.fit(random_matrix_array, random_matrix_array)
y_hat = lin_model.predict(random_matrix_array)
y_hat

AttributeError: 'NoneType' object has no attribute 'predict'

In [ ]:
Lagraunge 
maoitjsadl 

In [155]:
Linear = LinearRegression()
lin_model = Linear.fit(random_matrix_array, random_matrix_array)
y_hat = lin_model.predict(random_matrix_array)
y_hat

LinAlgError: 0-dimensional array given. Array must be at least two-dimensional

In [157]:
Linear = LinearRegression()
lin_model = Linear.fit(random_matrix_array, random_matrix_array)
y_hat = lin_model.predict(random_matrix_array)
y_hat

LinAlgError: Singular matrix

In [158]:
random_matrix_array[]

array([[0.20051783, 0.6910462 , 0.05572179, 0.05031819],
       [0.58273555, 0.68080108, 0.33454905, 0.56763461],
       [0.42751074, 0.699297  , 0.7957348 , 0.65174849]])

In [159]:
random_matrix_array[:]

array([[0.20051783, 0.6910462 , 0.05572179, 0.05031819],
       [0.58273555, 0.68080108, 0.33454905, 0.56763461],
       [0.42751074, 0.699297  , 0.7957348 , 0.65174849]])

In [160]:
random_matrix_array[1:]

array([[0.58273555, 0.68080108, 0.33454905, 0.56763461],
       [0.42751074, 0.699297  , 0.7957348 , 0.65174849]])

In [161]:
random_matrix_array[:1]

array([[0.20051783, 0.6910462 , 0.05572179, 0.05031819]])

In [ ]:

monte carlo

error propagation


recursive procedures

.001 in every collision
billion of collistions

compiling error



In [164]:
Linear = LinearRegression()
lin_model = Linear.fit(random_matrix_array,random_matrix_array[:1])
y_hat = lin_model.predict(random_matrix_array)
y_hat

ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 1 is different from 3)

In [165]:
Linear = LinearRegression()
lin_model = Linear.fit(random_matrix_array[:1],random_matrix_array[:1])
y_hat = lin_model.predict(random_matrix_array)
y_hat

LinAlgError: Singular matrix

In [166]:
Linear = LinearRegression()
lin_model = Linear.fit(random_matrix_array[:2],random_matrix_array[:1])
y_hat = lin_model.predict(random_matrix_array)
y_hab
t

ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 1 is different from 2)

In [ ]:
How matmul
how @ symbol 

In [167]:
Linear = LinearRegression()
lin_model = Linear.fit(random_matrix_array[:2],random_matrix_array[:2])
y_hat = lin_model.predict(random_matrix_array)
y_hat

AttributeError: 'NoneType' object has no attribute 'predict'

In [169]:
df = pd.read_csv('exNB.csv')
df

7.562675441204771687e+01  1.817044862628660553e+02  \
0                   70.540408                176.177640   
1                   76.875023                178.667364   
2                   70.225610                157.504877   
3                   74.106298                168.525499   
4                   76.507482                172.765822   
..                        ...                       ...   
994                 68.394140                141.464087   
995                 65.280727                138.177757   
996                 65.345827                135.199530   
997                 59.385331                152.598596   
998                 68.708487                129.957836   

     1.000000000000000000e+00  
0                         1.0  
1                         1.0  
2                         1.0  
3                         1.0  
4                         1.0  
..                        ...  
994                       0.0  
995                       0.0  
996                       0.0  
997                       0.0  
998                       0.0  

[999 rows x 3 columns]

In [170]:


df_h = pd.read_csv(r'C:\Users\Zebfred\Enhanced_IT\wk2_local_experiment\raw_house_data.csv')
df_h

FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\Zebfred\\Enhanced_IT\\wk2_local_experiment\\raw_house_data.csv'

In [171]:


df_h = pd.read_csv(r'raw_house_data.csv')
df_h

FileNotFoundError: [Errno 2] No such file or directory: 'raw_house_data.csv'

In [172]:


df_h = pd.read_csv(r'C:\Users\Zebfred\Enhanced_IT\wk2_local_experiment\raw_house_data.csv')
df_h

FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\Zebfred\\Enhanced_IT\\wk2_local_experiment\\raw_house_data.csv'

In [173]:
df_h = pd.read_csv(r'wk2_local_experiment/raw_house_data/raw_house_data.csv')
df_h

FileNotFoundError: [Errno 2] No such file or directory: 'wk2_local_experiment/raw_house_data/raw_house_data.csv'

In [174]:
df_h = pd.read_csv('raw_house_data.csv')
df_h

FileNotFoundError: [Errno 2] No such file or directory: 'raw_house_data.csv'

In [175]:
df_h = pd.read_csv('./raw_house_data.csv')
df_h

FileNotFoundError: [Errno 2] No such file or directory: './raw_house_data.csv'