In [6]:
import pandas as pd
data = { 'x1': [0,1,0,1],
         'x2': [0,0,1,1],
         'y':  [1,1,1,0]
       }

df = pd.DataFrame.from_dict(data).astype('int')

In [ ]:
# perceptron code that can correctly classify (99.0% accuracy) a NAND gate. 
#y = w1*x1 + w2*x2 + b
b = 1

In [8]:
def sigmoid(x):
    return 1 / (1 + np.exp(-x))

def sigmoid_derivate(x):
    sx = sigmoid(x)
    return sx * (1-sx)


In [9]:
df

x1  x2  y
0   0   0  1
1   1   0  1
2   0   1  1
3   1   1  0

In [2]:
import numpy as np
weights = 2 * np.random.random((3,1)) - 1

In [3]:
weights

array([[-0.5998353 ],
       [ 0.27483537],
       [ 0.28569364]])

In [15]:
weighted_sum = np.dot(df, weights)
weighted_sum

array([[ 0.28569364],
       [-0.31414165],
       [ 0.56052901],
       [-0.32499993]])

In [13]:
activated_output = sigmoid(weighted_sum)
activated_output
# true values [1,1,1,0]

array([[0.57094154],
       [0.42210413],
       [0.63657493],
       [0.41945771]])

In [22]:
correct_output = np.array([[1],[1],[1],[0]])
correct_output

array([[1],
       [1],
       [1],
       [0]])

In [23]:
error = correct_output - activated_output
error

array([[ 0.42905846],
       [ 0.57789587],
       [ 0.36342507],
       [-0.41945771]])

In [25]:
adjusted = error = sigmoid_derivate(activated_output)
adjusted 

array([[0.23068445],
       [0.23918678],
       [0.22629053],
       [0.23931806]])

In [27]:
weights += np.dot(df.T, adjusted)