In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

from scipy.stats import multivariate_normal as mvn

%matplotlib inline

In [9]:
import numpy as np

data_train = np.load('kmnist-train-imgs.npz', allow_pickle=True)
lst = data_train.files

for item in lst:
    print(item)
    print(data_train[item])

arr_0
[[[  0   0   0 ...   0   0   0]
  [  0   0   0 ...   0   0   0]
  [  0   0   0 ...   0   0   0]
  ...
  [  0   0   0 ...   0   0   0]
  [  0   0   0 ...   0   0   0]
  [  0   0   0 ...   0   0   0]]

 [[  0   0   0 ...   0   0   0]
  [  0   0   0 ...   0   0   0]
  [  0   0   0 ...   0   0   0]
  ...
  [  0   0   0 ...   0   0   0]
  [  0   0   0 ...   0   0   0]
  [  0   0   0 ...   0   0   0]]

 [[  0   0   0 ...   0   0   0]
  [  0   0   0 ...   0   0   0]
  [  0   0   0 ...   0   0   0]
  ...
  [  0   0   0 ...   0   0   0]
  [  0   0   0 ...   0   0   0]
  [  0   0   0 ...   0   0   0]]

 ...

 [[  0   0   0 ...   0   0   0]
  [  0   0   0 ...   0   0   0]
  [ 83 147 126 ... 145  49   0]
  ...
  [  0   0   0 ...   0   0   0]
  [  0   0   0 ...   0   0   0]
  [  0   0   0 ...   0   0   0]]

 [[  0   0   0 ...   0   0   0]
  [  0   0   1 ...   0   0   0]
  [  0   0   2 ...   0   0   0]
  ...
  [  0   0   0 ...   0   0   0]
  [  0   0   0 ...   0   0   0]
  [  0   0   0 ...   0

In [5]:
import numpy as np

data_test = np.load('kmnist-test-imgs.npz', allow_pickle=True)
lst = data_test.files

for item in lst:
    print(item)
    print(data_test[item])

arr_0
[[[  0  97  35 ...   0   0   0]
  [  0  34 143 ...   0   0   0]
  [  0   0  49 ...   0   0   0]
  ...
  [  0 126 254 ...   0   0   0]
  [  0  15 224 ...   0   0   0]
  [  0   0  68 ...   0   0   0]]

 [[  0   0   0 ...   0   0   0]
  [  0   0   0 ...   0   0   0]
  [  0   0   0 ...   0   0   0]
  ...
  [  0   0   0 ...   0   0   0]
  [  0   0   0 ...   0   0   0]
  [  0   0   0 ...   0   0   0]]

 [[  0   0   0 ...   0   0   0]
  [  0   0   0 ...   0   0   0]
  [  0   0   0 ...   0   0   0]
  ...
  [  0   0   0 ...   0   0   0]
  [  0   0   0 ...   0   0   0]
  [  0   0   0 ...   0   0   0]]

 ...

 [[  0   0   0 ...   0   0   0]
  [  0   0   0 ...   0   0   0]
  [  0   0   0 ...   0   0   0]
  ...
  [  0   0   0 ...   0   0   0]
  [  0   0   0 ...   0   0   0]
  [  0   0   0 ...   0   0   0]]

 [[  0   0   0 ...   0   0   0]
  [  0   0   0 ...   0   0   0]
  [  0   0   0 ...   0   0   0]
  ...
  [  0   0   0 ...  46  28  28]
  [  0   0   0 ...   0   0   0]
  [  0   0   0 ...   0

In [6]:
import numpy as np

data_test_label = np.load('kmnist-test-labels.npz', allow_pickle=True)
lst = data_test_label.files

for item in lst:
    print(item)
    print(data_test_label[item])

arr_0
[2 9 3 ... 9 4 2]


In [7]:
import numpy as np

data_train_labels = np.load('kmnist-train-labels.npz', allow_pickle=True)
lst = data_train_labels.files

for item in lst:
    print(item)
    print(data_train_labels[item])

arr_0
[8 7 0 ... 0 4 9]


In [11]:
df_train = pd.read_table("train-images-idx3-ubyte.gz",compression='gzip',sep='\x01')
df_trainb


UnicodeDecodeError: 'utf-8' codec can't decode byte 0xea in position 6: invalid continuation byte

In [12]:
arr = np.load('kmnist-train-imgs.npz')['arr_0']

In [15]:
type(arr[0])

numpy.ndarray

In [10]:
df_train = pd.DataFrame.from_dict({item: data_train[item] for item in data_train.files}, orient='index')
df_train

ValueError: Must pass 2-d input. shape=(1, 60000, 28, 28)