In [1]:
data = load('kmnist-test-imgs.npz')
lst = data.files
for item in lst:
    print(item)
    print(data[item])

NameError: name 'load' is not defined

In [2]:
import numpy as np

with np.load('kmnist-test-imgs.npz') as data:
    a = data['a']

KeyError: 'a is not a file in the archive'

In [4]:
import numpy as np

data = np.load('kmnist-test-imgs.npz', allow_pickle=True)
lst = data.files

for item in lst:
    print(item)
    print(data[item])

arr_0
[[[  0  97  35 ...   0   0   0]
  [  0  34 143 ...   0   0   0]
  [  0   0  49 ...   0   0   0]
  ...
  [  0 126 254 ...   0   0   0]
  [  0  15 224 ...   0   0   0]
  [  0   0  68 ...   0   0   0]]

 [[  0   0   0 ...   0   0   0]
  [  0   0   0 ...   0   0   0]
  [  0   0   0 ...   0   0   0]
  ...
  [  0   0   0 ...   0   0   0]
  [  0   0   0 ...   0   0   0]
  [  0   0   0 ...   0   0   0]]

 [[  0   0   0 ...   0   0   0]
  [  0   0   0 ...   0   0   0]
  [  0   0   0 ...   0   0   0]
  ...
  [  0   0   0 ...   0   0   0]
  [  0   0   0 ...   0   0   0]
  [  0   0   0 ...   0   0   0]]

 ...

 [[  0   0   0 ...   0   0   0]
  [  0   0   0 ...   0   0   0]
  [  0   0   0 ...   0   0   0]
  ...
  [  0   0   0 ...   0   0   0]
  [  0   0   0 ...   0   0   0]
  [  0   0   0 ...   0   0   0]]

 [[  0   0   0 ...   0   0   0]
  [  0   0   0 ...   0   0   0]
  [  0   0   0 ...   0   0   0]
  ...
  [  0   0   0 ...  46  28  28]
  [  0   0   0 ...   0   0   0]
  [  0   0   0 ...   0

In [5]:
import numpy as np

data = np.load('kmnist-test-labels.npz', allow_pickle=True)
lst = data.files

for item in lst:
    print(item)
    print(data[item])

arr_0
[2 9 3 ... 9 4 2]


In [ ]:
60,000

10,000

0-27

In [6]:
import numpy as np

data = np.load('kmnist-train-labels.npz', allow_pickle=True)
lst = data.files

for item in lst:
    print(item)
    print(data[item])

arr_0
[8 7 0 ... 0 4 9]


Kuzushiji-MNIST is a drop-in replacement for the MNIST dataset (28x28 grayscale, 70,000 images), provided in the original MNIST format as well as a NumPy format. Since MNIST restricts us to 10 classes, we chose one character to represent each of the 10 rows of Hiragana when creating Kuzushiji-MNIST.

Kuzushiji-49, as the name suggests, has 49 classes (28x28 grayscale, 270,912 images), is a much larger, but imbalanced dataset containing 48 Hiragana characters and one Hiragana iteration mark.

Kuzushiji-Kanji is an imbalanced dataset of total 3832 Kanji characters (64x64 grayscale, 140,426 images), ranging from 1,766 examples to only a single example per class.

In [7]:
import numpy as np

data = np.load('kmnist-train-imgs.npz', allow_pickle=True)
lst = data.files

for item in lst:
    print(item)
    print(data[item])

arr_0
[[[  0   0   0 ...   0   0   0]
  [  0   0   0 ...   0   0   0]
  [  0   0   0 ...   0   0   0]
  ...
  [  0   0   0 ...   0   0   0]
  [  0   0   0 ...   0   0   0]
  [  0   0   0 ...   0   0   0]]

 [[  0   0   0 ...   0   0   0]
  [  0   0   0 ...   0   0   0]
  [  0   0   0 ...   0   0   0]
  ...
  [  0   0   0 ...   0   0   0]
  [  0   0   0 ...   0   0   0]
  [  0   0   0 ...   0   0   0]]

 [[  0   0   0 ...   0   0   0]
  [  0   0   0 ...   0   0   0]
  [  0   0   0 ...   0   0   0]
  ...
  [  0   0   0 ...   0   0   0]
  [  0   0   0 ...   0   0   0]
  [  0   0   0 ...   0   0   0]]

 ...

 [[  0   0   0 ...   0   0   0]
  [  0   0   0 ...   0   0   0]
  [ 83 147 126 ... 145  49   0]
  ...
  [  0   0   0 ...   0   0   0]
  [  0   0   0 ...   0   0   0]
  [  0   0   0 ...   0   0   0]]

 [[  0   0   0 ...   0   0   0]
  [  0   0   1 ...   0   0   0]
  [  0   0   2 ...   0   0   0]
  ...
  [  0   0   0 ...   0   0   0]
  [  0   0   0 ...   0   0   0]
  [  0   0   0 ...   0